### PR TITLE
Allow path (build context) to be overridden

### LINKED ISSUE #80: Support setting context path for build_docker_image
There might be a reason why it was decided to hard code the "path" build kwarg and not the others, but for my use case it would be really useful to be able to set the context path in my `project.yaml` instead of it being set to `os.getcwd()`

This is because I have a template dockerfile used across multiple prefect projects which sits in a directory a few levels higher than each of the `project.yaml` files. 

The change would just be a one-liner @ deployments/steps.py:line175:
```
build_kwargs["path"] = build_kwargs.get("path", os.getcwd())
```

Thanks!

### PR DESCRIPTION
**Pull request by kvalenti**
This change allows users to manually define the build context location for situations where the current working directory is not desired.

Closes #80 

### Example

build:
- prefect_docker.deployments.steps.build_docker_image:
    id: build_image
    requires: prefect-docker>=0.3.11
    image_name: testengine
    tag: v1
    dockerfile: ./engine/dockerfile
    push: False
    path: /home/kvalenti/core

### Checklist

- [X] This pull request references any related issue by including "Closes #<ISSUE_NUMBER>"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect-docker/issues/new/choose) first.
- [ ] This pull request includes tests or only affects documentation.
- [ ] Summarized PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-docker/blob/main/CHANGELOG.md)

### CODE REVIEW

**Comment by tsugliani** [comment]
Hi @desertaxle 

Do you know if something is blocking this PR/Review ? 

Any progress on this PR would be greatly appreciated :-)

**Comment by desertaxle** [comment]
Thanks for the contribution @kvalenti! Can you please write a test covering this new functionality and add an entry to the changelog?

**Comment by Ponsaille** [comment]
Hi @kvalenti,

Thank you for this addition, in particular because I need it for my job. Do you knoe if you'll have time to make the final changes necessary for it to be merge?

If you don't have. I would be happy to do those.

**Comment by fhaase2** [comment]
Any update on this @desertaxle? This is urgently needed :) Thanks for any update!

**Review by desertaxle — APPROVED** [review]

**Pull request merged**
